(()=>{
  if(typeof api!=='function') return;
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const money=p=>'₹'+(Number(p||0)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
  const fmt=v=>v?new Date(v).toLocaleString('en-IN'):'—';
  const msg=(id,t,e=false)=>{const x=document.getElementById(id);if(x){x.textContent=t;x.className='status'+(e?' error':'')}};
  const table=(heads,rows)=>`<div class="table-wrap"><table class="table"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="20" class="small">No records found.</td></tr>'}</tbody></table></div>`;
  function page(id,title,body){const p=document.getElementById(id);if(!p)return null;p.innerHTML=`<div class="card"><div class="toolbar"><div><h2>${title}</h2><p class="small">Live production data. All writes are server-authorized and audited.</p></div><button class="ghost" id="${id}Refresh">↻ Refresh</button></div><div id="${id}Status" class="status">Loading…</div>${body}</div>`;return p}
  page('promos','🎟️ Promotions & rewards',`<div class="grid" style="margin-top:14px"><div class="card"><h3>Coupons</h3><div class="actions"><button class="primary" id="couponAdd">+ New coupon</button></div><div id="couponBody"></div></div><div class="card"><h3>Referrals</h3><div id="referralBody"></div></div><div class="card"><h3>Gift cards</h3><div class="actions"><button class="primary" id="giftAdd">+ Issue gift card</button></div><div id="giftBody"></div></div><div class="card"><h3>Wallet & loyalty</h3><div id="rewardBody"></div></div></div>`);
  async function loadPromos(){try{msg('promosStatus','Loading promotions…');const [c,r,g,w]=await Promise.all([api('/v1/admin/growth/coupons?limit=500'),api('/v1/admin/growth/referrals?limit=500'),api('/v1/admin/growth/gift-cards?limit=500'),api('/v1/admin/growth/rewards?limit=500')]);document.getElementById('couponBody').innerHTML=table(['Code','Discount','Window','Active','Actions'],(c.coupons||[]).map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${x.discount_type==='percent'?esc(x.discount_value)+'%':money(x.discount_value)}</td><td>${fmt(x.starts_at)} → ${fmt(x.ends_at)}</td><td>${x.is_active?'ACTIVE':'OFF'}</td><td><button class="ghost coupon-toggle" data-id="${esc(x.id)}" data-next="${!x.is_active}">${x.is_active?'Disable':'Enable'}</button></td></tr>`).join(''));document.getElementById('referralBody').innerHTML=table(['Code','Status','Created'],(r.referrals||[]).map(x=>`<tr><td>${esc(x.code)}</td><td>${esc(x.status)}</td><td>${fmt(x.created_at)}</td></tr>`).join(''));document.getElementById('giftBody').innerHTML=table(['Balance','Expiry','Active'],(g.gift_cards||[]).map(x=>`<tr><td>${money(x.balance_paise)}</td><td>${fmt(x.expires_at)}</td><td>${x.is_active?'ACTIVE':'OFF'}</td></tr>`).join(''));document.getElementById('rewardBody').innerHTML=table(['Customer','Wallet','Points'],(w.wallets||[]).map(x=>{const l=(w.loyalty||[]).find(y=>y.customer_id===x.customer_id);return `<tr><td>${esc(x.customer_id)}</td><td>${money(x.balance_paise)}</td><td>${Number(l?.points||0)}</td></tr>`}).join(''));document.querySelectorAll('.coupon-toggle').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/v1/admin/growth/coupons/'+encodeURIComponent(b.dataset.id),{method:'PATCH',body:JSON.stringify({is_active:b.dataset.next==='true'})});await loadPromos()}catch(e){alert(e.message||'Coupon update failed')}finally{b.disabled=false}});msg('promosStatus','Promotion, referral, gift-card and reward data loaded.')}catch(e){msg('promosStatus',e.message||'Unable to load promotion data',true)}}
  document.getElementById('couponAdd')?.addEventListener('click',async()=>{const code=prompt('Coupon code (A-Z, 0-9, _ or -)');if(!code)return;const type=prompt('Discount type: percent or fixed','percent');const value=Number(prompt(type==='percent'?'Percent discount':'Fixed discount in paise','10'));if(!Number.isInteger(value)||value<=0)return alert('Invalid discount value');try{await api('/v1/admin/growth/coupons',{method:'POST',body:JSON.stringify({code,discount_type:type,discount_value:value})});await loadPromos()}catch(e){alert(e.message||'Coupon creation failed')}});
  document.getElementById('giftAdd')?.addEventListener('click',async()=>{const code=prompt('Gift card code (store securely; only its hash is retained)');if(!code)return;const value=Number(prompt('Value in paise','1000'));if(!Number.isInteger(value)||value<100)return alert('Invalid value');try{await api('/v1/admin/growth/gift-cards',{method:'POST',body:JSON.stringify({code,value_paise:value})});alert('Gift card issued. Store the code securely; it cannot be recovered from Admin.');await loadPromos()}catch(e){alert(e.message||'Gift card creation failed')}});
  document.getElementById('promosRefresh')?.addEventListener('click',loadPromos);

  page('staff','🛡️ Staff & roles',`<div class="toolbar" style="margin-top:14px"><input id="staffLiveSearch" placeholder="Search email / role"><button class="primary" id="staffLiveRefresh">↻ Refresh</button></div><div id="staffLiveBody"></div>`);
  async function loadStaff(){try{msg('staffStatus','Loading staff…');const d=await api('/v1/admin/staff');const q=(document.getElementById('staffLiveSearch')?.value||'').toLowerCase();const rows=(d.staff||[]).filter(x=>`${x.email} ${x.role}`.toLowerCase().includes(q));document.getElementById('staffLiveBody').innerHTML=table(['Email','Role','Active','Updated','Actions'],rows.map(x=>`<tr><td>${esc(x.email||x.user_id)}</td><td>${esc(x.role||'customer')}</td><td>${x.is_active?'ACTIVE':'DISABLED'}</td><td>${fmt(x.updated_at)}</td><td>${x.role!=='super_admin'?`<button class="ghost staff-role" data-id="${esc(x.user_id)}">Change role</button> <button class="ghost staff-active" data-id="${esc(x.user_id)}" data-next="${!x.is_active}">${x.is_active?'Disable':'Enable'}</button>`:'Protected'}</td></tr>`).join(''));document.querySelectorAll('.staff-active').forEach(b=>b.onclick=async()=>{try{await api('/v1/admin/staff/'+encodeURIComponent(b.dataset.id)+'/active',{method:'POST',body:JSON.stringify({is_active:b.dataset.next==='true'})});await loadStaff()}catch(e){alert(e.message||'Staff status update failed')}});document.querySelectorAll('.staff-role').forEach(b=>b.onclick=async()=>{const role=prompt('Role: admin_manager, store_manager, billing_staff, order_staff, inventory_staff, content_manager, support_staff, review_moderator, report_viewer');if(!role)return;try{await api('/v1/admin/staff/'+encodeURIComponent(b.dataset.id)+'/role',{method:'POST',body:JSON.stringify({role})});await loadStaff()}catch(e){alert(e.message||'Role update failed')}});msg('staffStatus',`${rows.length} staff records loaded.`)}catch(e){msg('staffStatus',e.message||'Unable to load staff',true)}}
  document.getElementById('staffLiveRefresh')?.addEventListener('click',loadStaff);document.getElementById('staffLiveSearch')?.addEventListener('input',loadStaff);

  page('settings','⚙️ Operational settings',`<div class="toolbar" style="margin-top:14px"><button class="primary" id="settingsRefresh">↻ Reload</button></div><div id="settingsLiveBody"></div>`);
  async function loadSettings(){try{msg('settingsStatus','Loading settings…');const d=await api('/v1/admin/settings');const rows=d.settings||[];document.getElementById('settingsLiveBody').innerHTML=table(['Key','Value','Updated'],rows.map(x=>`<tr><td><b>${esc(x.key)}</b></td><td><code>${esc(JSON.stringify(x.value))}</code></td><td>${fmt(x.updated_at)}</td></tr>`).join(''))+`<div class="section card"><h3>Update protected setting</h3><div class="toolbar"><input id="settingKey" placeholder="setting key"><input id="settingValue" placeholder='JSON value, e.g. true or {"x":1}'><button class="primary" id="settingSave">Save</button></div></div>`;document.getElementById('settingSave').onclick=async()=>{try{const key=document.getElementById('settingKey').value.trim();const raw=document.getElementById('settingValue').value;const value=JSON.parse(raw);await api('/v1/admin/settings',{method:'PATCH',body:JSON.stringify({key,value})});await loadSettings()}catch(e){alert(e.message||'Setting update failed')}};msg('settingsStatus',`${rows.length} settings loaded.`)}catch(e){msg('settingsStatus',e.message||'Unable to load settings',true)}}
  document.getElementById('settingsRefresh')?.addEventListener('click',loadSettings);
  window.__DTGrowth={loadPromos,loadStaff,loadSettings};
  document.querySelectorAll('.nav button[data-page]').forEach(b=>{const old=b.onclick;b.onclick=()=>{if(old)old.call(b);if(b.dataset.page==='promos')loadPromos();if(b.dataset.page==='staff')loadStaff();if(b.dataset.page==='settings')loadSettings()}});
  setTimeout(()=>{loadPromos();loadStaff();loadSettings()},700);
})();
