(() => {
  const page=document.getElementById('products');if(!page||typeof api!=='function')return;
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const money=p=>'₹'+(Number(p||0)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
  const canWrite=()=>{try{return state.ctx?.permissions?.includes('products.write')}catch{return false}};
  let products=[];
  page.innerHTML='<div class="card"><div class="toolbar"><div><h2>Products & variants</h2><p class="small">Each sellable pack is a separate variant with its own SKU, price and stock ledger.</p></div><button class="primary" id="prodAdd" data-perm="products.write">+ Add product</button></div><div id="prodStatus" class="status">Loading catalog…</div></div><div class="section card"><div class="toolbar"><input id="prodSearch" placeholder="Search product, pack or SKU"><span class="small">Variants are what customers actually add to cart.</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Variant / pack</th><th>SKU</th><th>Price</th><th>Threshold</th><th>Active</th><th>Action</th></tr></thead><tbody id="prodRows"></tbody></table></div></div><div id="prodModal" class="login hidden"><div class="loginbox" style="width:min(620px,100%)"><h2 id="prodModalTitle">Add product</h2><div class="field"><label>Product name</label><input id="pName"></div><div class="field"><label>Description</label><textarea id="pDesc" style="min-height:100px"></textarea></div><div class="field"><label>Slug</label><input id="pSlug"></div><div class="field"><label>Category ID (optional)</label><input id="pCategory"></div><div class="actions"><button class="primary" id="pSave">Save product</button><button class="ghost" id="pCancel">Cancel</button></div><div id="pStatus" class="status"></div></div></div><div id="varModal" class="login hidden"><div class="loginbox" style="width:min(560px,100%)"><h2 id="varTitle">Add variant</h2><p id="varProduct" class="small"></p><div class="field"><label>Variant name</label><input id="vName" placeholder="50 g"></div><div class="field"><label>SKU</label><input id="vSku" placeholder="CHM-50G"></div><div class="field"><label>Price (₹)</label><input id="vPrice" type="number" step="0.01" min="0"></div><div class="field"><label>Compare-at price (₹)</label><input id="vCompare" type="number" step="0.01" min="0"></div><div class="field"><label>Pack size</label><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="vPack" type="number" step="0.001" min="0" placeholder="50"><select id="vUnit"><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="l">l</option><option value="pcs">pcs</option></select></div></div><div class="field"><label>Low-stock threshold (units)</label><input id="vThreshold" type="number" step="1" min="0" value="5"></div><div class="actions"><button class="primary" id="vSave">Save variant</button><button class="ghost" id="vCancel">Cancel</button></div><div id="vStatus" class="status"></div></div></div>';
  const st=(id,t,e=false)=>{const x=document.getElementById(id);if(x){x.textContent=t;x.className='status'+(e?' error':'')}};
  const render=()=>{const q=(document.getElementById('prodSearch').value||'').toLowerCase().trim();const flat=[];products.forEach(p=>(p.product_variants||[]).forEach(v=>flat.push({p,v})));const rows=flat.filter(x=>(x.p.name+' '+x.v.name+' '+(x.v.sku||'')).toLowerCase().includes(q));document.getElementById('prodRows').innerHTML=rows.length?rows.map(({p,v})=>`<tr><td><b>${esc(p.name)}</b><div class="small">${esc(p.slug||'')}</div></td><td>${esc(v.pack_size_value?`${v.pack_size_value} ${v.pack_size_unit||''}`:v.name)}</td><td>${esc(v.sku||'—')}</td><td>${money(v.price_paise)}</td><td>${Number(v.stock_threshold||0)}</td><td><span class="badge">${v.is_active?'ACTIVE':'INACTIVE'}</span></td><td><button class="ghost" data-edit-var="${esc(v.id)}">Edit variant</button></td></tr>`).join(''):'<tr><td colspan="7" class="small">No products or variants found.</td></tr>';document.querySelectorAll('[data-edit-var]').forEach(b=>b.onclick=()=>openVariant(null,b.dataset.editVar));};
  async function load(){try{st('prodStatus','Loading catalog…');const x=await api('/v1/admin/catalog/products');products=x.products||[];render();st('prodStatus',products.length+' product'+(products.length===1?'':'s')+' loaded.');}catch(e){st('prodStatus',e.message||'Unable to load catalog',true)}}
  let editVariant=null;
  function openVariant(productId,variantId){let p,v;if(variantId){for(const pp of products){const vv=(pp.product_variants||[]).find(x=>x.id===variantId);if(vv){p=pp;v=vv;break}}}else p=products.find(x=>x.id===productId);if(!p)return;editVariant=v||null;document.getElementById('varTitle').textContent=v?'Edit variant':'Add variant';document.getElementById('varProduct').textContent=p.name;document.getElementById('vName').value=v?.name||'';document.getElementById('vSku').value=v?.sku||'';document.getElementById('vPrice').value=v?(Number(v.price_paise||0)/100):'';document.getElementById('vCompare').value=v?.compare_at_price_paise?Number(v.compare_at_price_paise)/100:'';document.getElementById('vPack').value=v?.pack_size_value||'';document.getElementById('vUnit').value=v?.pack_size_unit||'g';document.getElementById('vThreshold').value=v?.stock_threshold??5;document.getElementById('varModal').dataset.product=p.id;document.getElementById('varModal').classList.remove('hidden');st('vStatus','')}
  document.getElementById('prodAdd').onclick=()=>{if(!canWrite())return;document.getElementById('pName').value='';document.getElementById('pDesc').value='';document.getElementById('pSlug').value='';document.getElementById('pCategory').value='';document.getElementById('prodModal').classList.remove('hidden');st('pStatus','')};
  document.getElementById('pCancel').onclick=()=>document.getElementById('prodModal').classList.add('hidden');
  document.getElementById('pSave').onclick=async()=>{try{const name=document.getElementById('pName').value.trim();if(!name)throw new Error('Product name is required');const x=await api('/v1/admin/catalog/products',{method:'POST',body:JSON.stringify({name,description:document.getElementById('pDesc').value,slug:document.getElementById('pSlug').value,category_id:document.getElementById('pCategory').value||null})});document.getElementById('prodModal').classList.add('hidden');await load();if(x.product?.id)openVariant(x.product.id,null)}catch(e){st('pStatus',e.message||'Unable to save product',true)}};
  document.getElementById('vCancel').onclick=()=>document.getElementById('varModal').classList.add('hidden');
  document.getElementById('vSave').onclick=async()=>{try{const product_id=document.getElementById('varModal').dataset.product;const body={product_id,name:document.getElementById('vName').value.trim(),sku:document.getElementById('vSku').value.trim()||null,price_paise:Math.round(Number(document.getElementById('vPrice').value||0)*100),compare_at_price_paise:document.getElementById('vCompare').value?Math.round(Number(document.getElementById('vCompare').value)*100):null,pack_size_value:document.getElementById('vPack').value?Number(document.getElementById('vPack').value):null,pack_size_unit:document.getElementById('vPack').value?document.getElementById('vUnit').value:null,stock_threshold:Math.max(0,Math.floor(Number(document.getElementById('vThreshold').value||0)))};if(!body.name)throw new Error('Variant name is required');if(body.price_paise<0)throw new Error('Price cannot be negative');const path=editVariant?'/v1/admin/catalog/variants/'+encodeURIComponent(editVariant.id):'/v1/admin/catalog/variants';await api(path,{method:editVariant?'PATCH':'POST',body:JSON.stringify(editVariant?{name:body.name,sku:body.sku,price_paise:body.price_paise,compare_at_price_paise:body.compare_at_price_paise,pack_size_value:body.pack_size_value,pack_size_unit:body.pack_size_unit,stock_threshold:body.stock_threshold}:body)});document.getElementById('varModal').classList.add('hidden');await load()}catch(e){st('vStatus',e.message||'Unable to save variant',true)}};
  document.getElementById('prodSearch').oninput=render;
  window.DTProducts={load};window.addEventListener('load',()=>setTimeout(load,300),{once:true});
})();
